## 异常与错误

![image-20211221105633929](C:\Users\千江映月\AppData\Roaming\Typora\typora-user-images\image-20211221105633929.png)

- 语法错误（SyntaxError）

- 异常

  - 自定义异常

    - `raise`

      ```python
      x = 10
      if x > 5:
          raise Exception('x should not exceed 5. The value of x was: {}'.format(x))
          # raise ValueError("输入值过大")
      ```

      输出：

      ```
      Traceback (most recent call last):
        File "<input>", line 3, in <module>
      Exception: x should not exceed 5. The value of x was: 10
      ```

    - `assert` : AssertionError

      ```python
      import sys
      assert ('linux' in sys.platform), "This code runs on Linux only."
      ```

      输出：

      ```python
      Traceback (most recent call last):
        File "<input>", line 2, in <module>
      AssertionError: This code runs on Linux only.
      ```

    - 

  - 执行异常

    ![image-20211221105813348](C:\Users\千江映月\AppData\Roaming\Typora\typora-user-images\image-20211221105813348.png)

    - Exception

      ```python
      import sys
      
      
      def linux_interaction():
          assert ('windows' in sys.platform), "Function can only run on Linux systems."
          print('Doing something.')
      
          
      try:
          linux_interaction()
      # except AssertionError as error:
      # except: # 直接排除所有异常情况，也不做异常情况输出。
      except Exception as error: # 排除所有异常，并使用别名，返回异常异常信息。
          print(error)
      else: # 无异常抛出时执行
          try:
              with open('file.log') as file:
                  read_data = file.read()
          except FileNotFoundError as fnf_error:
              print(fnf_error)
      finally: # 无论是否存在异常都会执行
          print('Cleaning up, irrespective of any exceptions.')    
          
      ```

      

    - 

